//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba2.testeo
{

    public partial class GeneralXpObject1 : XPObject
    {
        string fid;
        public string id
        {
            get { return fid; }
            set { SetPropertyValue<string>(nameof(id), ref fid, value); }
        }
    }

}
