//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba2.testeo
{

    [Persistent(@"usuarios")]
    public partial class Usuarios : XPLiteObject
    {
        int fidUsuarios;
        [Key]
        public int idUsuarios
        {
            get { return fidUsuarios; }
            set { SetPropertyValue<int>(nameof(idUsuarios), ref fidUsuarios, value); }
        }
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fEdad;
        public string Edad
        {
            get { return fEdad; }
            set { SetPropertyValue<string>(nameof(Edad), ref fEdad, value); }
        }
    }

}
