//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace systemafacturacion.Libreria
{

    public partial class Roles : XPObject
    {
        string fIdroles;
        public string Idroles
        {
            get { return fIdroles; }
            set { SetPropertyValue<string>(nameof(Idroles), ref fIdroles, value); }
        }
        string fTiporole;
        public string Tiporole
        {
            get { return fTiporole; }
            set { SetPropertyValue<string>(nameof(Tiporole), ref fTiporole, value); }
        }
        string fIdusuario;
        public string Idusuario
        {
            get { return fIdusuario; }
            set { SetPropertyValue<string>(nameof(Idusuario), ref fIdusuario, value); }
        }
    }

}
