//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace systemafacturacion.Libreria
{

    public partial class Usuario : XPObject
    {
        string fIdusuario;
        public string Idusuario
        {
            get { return fIdusuario; }
            set { SetPropertyValue<string>(nameof(Idusuario), ref fIdusuario, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fClave;
        public string Clave
        {
            get { return fClave; }
            set { SetPropertyValue<string>(nameof(Clave), ref fClave, value); }
        }
    }

}
