//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba.prueba
{

    [Persistent(@"arreglopago")]
    public partial class Arreglopago : XPLiteObject
    {
        int fidarreglopago;
        [Key(true)]
        public int idarreglopago
        {
            get { return fidarreglopago; }
            set { SetPropertyValue<int>(nameof(idarreglopago), ref fidarreglopago, value); }
        }
        DateTime ffecha;
        public DateTime fecha
        {
            get { return ffecha; }
            set { SetPropertyValue<DateTime>(nameof(fecha), ref ffecha, value); }
        }
        DateTime ffechapago;
        public DateTime fechapago
        {
            get { return ffechapago; }
            set { SetPropertyValue<DateTime>(nameof(fechapago), ref ffechapago, value); }
        }
        int fidcredito;
        [Indexed(Name = @"iidcredito_arreglopago")]
        public int idcredito
        {
            get { return fidcredito; }
            set { SetPropertyValue<int>(nameof(idcredito), ref fidcredito, value); }
        }
        sbyte factivo;
        public sbyte activo
        {
            get { return factivo; }
            set { SetPropertyValue<sbyte>(nameof(activo), ref factivo, value); }
        }
        string fnota;
        [Size(200)]
        public string nota
        {
            get { return fnota; }
            set { SetPropertyValue<string>(nameof(nota), ref fnota, value); }
        }
    }

}
