//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba.prueba
{

    [Persistent(@"autorizar_anulacion")]
    public partial class Autorizar_anulacion : XPLiteObject
    {
        int fidautorizar;
        [Key(true)]
        public int idautorizar
        {
            get { return fidautorizar; }
            set { SetPropertyValue<int>(nameof(idautorizar), ref fidautorizar, value); }
        }
        DateTime ffecha;
        public DateTime fecha
        {
            get { return ffecha; }
            set { SetPropertyValue<DateTime>(nameof(fecha), ref ffecha, value); }
        }
        int fidcredito;
        [Indexed(Name = @"iidcredito_autorizar_anulacion")]
        public int idcredito
        {
            get { return fidcredito; }
            set { SetPropertyValue<int>(nameof(idcredito), ref fidcredito, value); }
        }
        int fidusuario1;
        [Indexed(Name = @"iidusuario1_autorizar_anulacion")]
        public int idusuario1
        {
            get { return fidusuario1; }
            set { SetPropertyValue<int>(nameof(idusuario1), ref fidusuario1, value); }
        }
        int fidusuario2;
        [Indexed(Name = @"iidusuario2_autorizar_anulacion")]
        public int idusuario2
        {
            get { return fidusuario2; }
            set { SetPropertyValue<int>(nameof(idusuario2), ref fidusuario2, value); }
        }
        int fidusuario3;
        [Indexed(Name = @"iidusuario3_autorizar_anulacion")]
        public int idusuario3
        {
            get { return fidusuario3; }
            set { SetPropertyValue<int>(nameof(idusuario3), ref fidusuario3, value); }
        }
        int festado;
        public int estado
        {
            get { return festado; }
            set { SetPropertyValue<int>(nameof(estado), ref festado, value); }
        }
        string fcomentario;
        [Size(200)]
        public string comentario
        {
            get { return fcomentario; }
            set { SetPropertyValue<string>(nameof(comentario), ref fcomentario, value); }
        }
        DateTime ffecha_resolucion;
        public DateTime fecha_resolucion
        {
            get { return ffecha_resolucion; }
            set { SetPropertyValue<DateTime>(nameof(fecha_resolucion), ref ffecha_resolucion, value); }
        }
    }

}
