//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba.prueba
{

    [Persistent(@"cliente")]
    public partial class Cliente : XPLiteObject
    {
        int fclienteid;
        [Key(true)]
        public int clienteid
        {
            get { return fclienteid; }
            set { SetPropertyValue<int>(nameof(clienteid), ref fclienteid, value); }
        }
        string fnombre;
        [Size(45)]
        public string nombre
        {
            get { return fnombre; }
            set { SetPropertyValue<string>(nameof(nombre), ref fnombre, value); }
        }
        string fapellido;
        [Size(45)]
        public string apellido
        {
            get { return fapellido; }
            set { SetPropertyValue<string>(nameof(apellido), ref fapellido, value); }
        }
        string fcedula;
        [Size(20)]
        public string cedula
        {
            get { return fcedula; }
            set { SetPropertyValue<string>(nameof(cedula), ref fcedula, value); }
        }
        string ftelefono;
        [Size(11)]
        public string telefono
        {
            get { return ftelefono; }
            set { SetPropertyValue<string>(nameof(telefono), ref ftelefono, value); }
        }
        string fdireccion;
        [Size(200)]
        public string direccion
        {
            get { return fdireccion; }
            set { SetPropertyValue<string>(nameof(direccion), ref fdireccion, value); }
        }
        int forden;
        public int orden
        {
            get { return forden; }
            set { SetPropertyValue<int>(nameof(orden), ref forden, value); }
        }
        string fcorreo;
        [Size(200)]
        public string correo
        {
            get { return fcorreo; }
            set { SetPropertyValue<string>(nameof(correo), ref fcorreo, value); }
        }
        Informacio_negocio fidnegocio;
        [Association(@"ClienteReferencesInformacio_negocio")]
        public Informacio_negocio idnegocio
        {
            get { return fidnegocio; }
            set { SetPropertyValue<Informacio_negocio>(nameof(idnegocio), ref fidnegocio, value); }
        }
        [Association(@"PrestamoReferencesCliente")]
        public XPCollection<Prestamo> Prestamoes { get { return GetCollection<Prestamo>(nameof(Prestamoes)); } }
        [Association(@"ReferenciasReferencesCliente")]
        public XPCollection<Referencias> ReferenciasCollection { get { return GetCollection<Referencias>(nameof(ReferenciasCollection)); } }
        [Association(@"TelefonoReferencesCliente")]
        public XPCollection<Telefono> Telefonoes { get { return GetCollection<Telefono>(nameof(Telefonoes)); } }
    }

}
