//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba.prueba
{

    [Persistent(@"cuotas")]
    public partial class Cuotas : XPLiteObject
    {
        int fcuentaid;
        [Key(true)]
        public int cuentaid
        {
            get { return fcuentaid; }
            set { SetPropertyValue<int>(nameof(cuentaid), ref fcuentaid, value); }
        }
        DateTime ffecha;
        public DateTime fecha
        {
            get { return ffecha; }
            set { SetPropertyValue<DateTime>(nameof(fecha), ref ffecha, value); }
        }
        float fmonto;
        public float monto
        {
            get { return fmonto; }
            set { SetPropertyValue<float>(nameof(monto), ref fmonto, value); }
        }
        Prestamo fprestamo_prestamoid;
        [Association(@"CuotasReferencesPrestamo")]
        public Prestamo prestamo_prestamoid
        {
            get { return fprestamo_prestamoid; }
            set { SetPropertyValue<Prestamo>(nameof(prestamo_prestamoid), ref fprestamo_prestamoid, value); }
        }
        int fnum_abono;
        public int num_abono
        {
            get { return fnum_abono; }
            set { SetPropertyValue<int>(nameof(num_abono), ref fnum_abono, value); }
        }
        int fmora;
        public int mora
        {
            get { return fmora; }
            set { SetPropertyValue<int>(nameof(mora), ref fmora, value); }
        }
        float fsaldo;
        public float saldo
        {
            get { return fsaldo; }
            set { SetPropertyValue<float>(nameof(saldo), ref fsaldo, value); }
        }
        float fpendiente;
        public float pendiente
        {
            get { return fpendiente; }
            set { SetPropertyValue<float>(nameof(pendiente), ref fpendiente, value); }
        }
        string ffechahora;
        [Size(45)]
        public string fechahora
        {
            get { return ffechahora; }
            set { SetPropertyValue<string>(nameof(fechahora), ref ffechahora, value); }
        }
    }

}
