//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba.prueba
{

    [Persistent(@"informacio_negocio")]
    public partial class Informacio_negocio : XPLiteObject
    {
        int fidnegocios;
        [Key(true)]
        public int idnegocios
        {
            get { return fidnegocios; }
            set { SetPropertyValue<int>(nameof(idnegocios), ref fidnegocios, value); }
        }
        string fnombre_negocio;
        [Size(200)]
        public string nombre_negocio
        {
            get { return fnombre_negocio; }
            set { SetPropertyValue<string>(nameof(nombre_negocio), ref fnombre_negocio, value); }
        }
        string factividad;
        [Size(45)]
        public string actividad
        {
            get { return factividad; }
            set { SetPropertyValue<string>(nameof(actividad), ref factividad, value); }
        }
        int fcantidad_trabajadores;
        public int cantidad_trabajadores
        {
            get { return fcantidad_trabajadores; }
            set { SetPropertyValue<int>(nameof(cantidad_trabajadores), ref fcantidad_trabajadores, value); }
        }
        int fanyos_experiencia;
        public int anyos_experiencia
        {
            get { return fanyos_experiencia; }
            set { SetPropertyValue<int>(nameof(anyos_experiencia), ref fanyos_experiencia, value); }
        }
        string ftenencia_de_local;
        [Size(45)]
        public string tenencia_de_local
        {
            get { return ftenencia_de_local; }
            set { SetPropertyValue<string>(nameof(tenencia_de_local), ref ftenencia_de_local, value); }
        }
        string fdireccion_negocio;
        [Size(200)]
        public string direccion_negocio
        {
            get { return fdireccion_negocio; }
            set { SetPropertyValue<string>(nameof(direccion_negocio), ref fdireccion_negocio, value); }
        }
        int fDB;
        public int DB
        {
            get { return fDB; }
            set { SetPropertyValue<int>(nameof(DB), ref fDB, value); }
        }
        int fDM;
        public int DM
        {
            get { return fDM; }
            set { SetPropertyValue<int>(nameof(DM), ref fDM, value); }
        }
        int fDP;
        public int DP
        {
            get { return fDP; }
            set { SetPropertyValue<int>(nameof(DP), ref fDP, value); }
        }
        string fnombre;
        [Size(200)]
        public string nombre
        {
            get { return fnombre; }
            set { SetPropertyValue<string>(nameof(nombre), ref fnombre, value); }
        }
        string fdireccion;
        [Size(200)]
        public string direccion
        {
            get { return fdireccion; }
            set { SetPropertyValue<string>(nameof(direccion), ref fdireccion, value); }
        }
        [Association(@"ClienteReferencesInformacio_negocio")]
        public XPCollection<Cliente> Clientes { get { return GetCollection<Cliente>(nameof(Clientes)); } }
    }

}
