//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba.prueba
{

    [Persistent(@"pagos")]
    public partial class Pagos : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        DateTime ffecha_pago;
        public DateTime fecha_pago
        {
            get { return ffecha_pago; }
            set { SetPropertyValue<DateTime>(nameof(fecha_pago), ref ffecha_pago, value); }
        }
        float fmonto;
        public float monto
        {
            get { return fmonto; }
            set { SetPropertyValue<float>(nameof(monto), ref fmonto, value); }
        }
        float fpagado;
        public float pagado
        {
            get { return fpagado; }
            set { SetPropertyValue<float>(nameof(pagado), ref fpagado, value); }
        }
        float fpendiente;
        public float pendiente
        {
            get { return fpendiente; }
            set { SetPropertyValue<float>(nameof(pendiente), ref fpendiente, value); }
        }
        Prestamo fprestamo;
        [Association(@"PagosReferencesPrestamo")]
        public Prestamo prestamo
        {
            get { return fprestamo; }
            set { SetPropertyValue<Prestamo>(nameof(prestamo), ref fprestamo, value); }
        }
    }

}
