//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba.prueba
{

    [Persistent(@"permissions")]
    public partial class Permissions : XPLiteObject
    {
        ulong fid;
        [Key]
        public ulong id
        {
            get { return fid; }
            set { SetPropertyValue<ulong>(nameof(id), ref fid, value); }
        }
        string fname;
        [Indexed(@"guard_name", Name = @"permissions_name_guard_name_unique", Unique = true)]
        [Size(255)]
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        string fguard_name;
        [Size(255)]
        public string guard_name
        {
            get { return fguard_name; }
            set { SetPropertyValue<string>(nameof(guard_name), ref fguard_name, value); }
        }
    }

}
