//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba.prueba
{

    [Persistent(@"users")]
    public partial class Users : XPLiteObject
    {
        ulong fid;
        [Key]
        public ulong id
        {
            get { return fid; }
            set { SetPropertyValue<ulong>(nameof(id), ref fid, value); }
        }
        string fname;
        [Size(255)]
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        string femail;
        [Indexed(Name = @"users_email_unique", Unique = true)]
        [Size(255)]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        string fpassword;
        [Size(255)]
        public string password
        {
            get { return fpassword; }
            set { SetPropertyValue<string>(nameof(password), ref fpassword, value); }
        }
        string fremember_token;
        public string remember_token
        {
            get { return fremember_token; }
            set { SetPropertyValue<string>(nameof(remember_token), ref fremember_token, value); }
        }
    }

}
