//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba1.prueba
{

    [Persistent(@"arquedo_diario")]
    public partial class Arquedo_diario : XPLiteObject
    {
        int fidarqueo;
        [Key(true)]
        public int idarqueo
        {
            get { return fidarqueo; }
            set { SetPropertyValue<int>(nameof(idarqueo), ref fidarqueo, value); }
        }
        DateTime ffecha;
        public DateTime fecha
        {
            get { return ffecha; }
            set { SetPropertyValue<DateTime>(nameof(fecha), ref ffecha, value); }
        }
        double fc1000;
        public double c1000
        {
            get { return fc1000; }
            set { SetPropertyValue<double>(nameof(c1000), ref fc1000, value); }
        }
        double fc500;
        public double c500
        {
            get { return fc500; }
            set { SetPropertyValue<double>(nameof(c500), ref fc500, value); }
        }
        double fc200;
        public double c200
        {
            get { return fc200; }
            set { SetPropertyValue<double>(nameof(c200), ref fc200, value); }
        }
        double fc100;
        public double c100
        {
            get { return fc100; }
            set { SetPropertyValue<double>(nameof(c100), ref fc100, value); }
        }
        double fc50;
        public double c50
        {
            get { return fc50; }
            set { SetPropertyValue<double>(nameof(c50), ref fc50, value); }
        }
        double fc20;
        public double c20
        {
            get { return fc20; }
            set { SetPropertyValue<double>(nameof(c20), ref fc20, value); }
        }
        double fc10;
        public double c10
        {
            get { return fc10; }
            set { SetPropertyValue<double>(nameof(c10), ref fc10, value); }
        }
        double fc5;
        public double c5
        {
            get { return fc5; }
            set { SetPropertyValue<double>(nameof(c5), ref fc5, value); }
        }
        double fc1;
        public double c1
        {
            get { return fc1; }
            set { SetPropertyValue<double>(nameof(c1), ref fc1, value); }
        }
        double ftotal;
        public double total
        {
            get { return ftotal; }
            set { SetPropertyValue<double>(nameof(total), ref ftotal, value); }
        }
        Cobrador fidcobrador;
        [Association(@"Arquedo_diarioReferencesCobrador")]
        public Cobrador idcobrador
        {
            get { return fidcobrador; }
            set { SetPropertyValue<Cobrador>(nameof(idcobrador), ref fidcobrador, value); }
        }
        double fdesembolso;
        public double desembolso
        {
            get { return fdesembolso; }
            set { SetPropertyValue<double>(nameof(desembolso), ref fdesembolso, value); }
        }
        double fc50centavos;
        public double c50centavos
        {
            get { return fc50centavos; }
            set { SetPropertyValue<double>(nameof(c50centavos), ref fc50centavos, value); }
        }
    }

}
