//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba1.prueba
{

    [Persistent(@"bitacora_credito")]
    public partial class Bitacora_credito : XPLiteObject
    {
        int fidbitacora;
        [Key(true)]
        public int idbitacora
        {
            get { return fidbitacora; }
            set { SetPropertyValue<int>(nameof(idbitacora), ref fidbitacora, value); }
        }
        DateTime ffecha;
        public DateTime fecha
        {
            get { return ffecha; }
            set { SetPropertyValue<DateTime>(nameof(fecha), ref ffecha, value); }
        }
        int fmovimiento;
        public int movimiento
        {
            get { return fmovimiento; }
            set { SetPropertyValue<int>(nameof(movimiento), ref fmovimiento, value); }
        }
        int fidcredito;
        [Indexed(Name = @"iidcredito_bitacora_credito")]
        public int idcredito
        {
            get { return fidcredito; }
            set { SetPropertyValue<int>(nameof(idcredito), ref fidcredito, value); }
        }
        int fidusuario;
        [Indexed(Name = @"iidusuario_bitacora_credito")]
        public int idusuario
        {
            get { return fidusuario; }
            set { SetPropertyValue<int>(nameof(idusuario), ref fidusuario, value); }
        }
    }

}
