//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba1.prueba
{

    [Persistent(@"failed_jobs")]
    public partial class Failed_jobs : XPLiteObject
    {
        ulong fid;
        [Key]
        public ulong id
        {
            get { return fid; }
            set { SetPropertyValue<ulong>(nameof(id), ref fid, value); }
        }
        string fuuid;
        [Indexed(Name = @"failed_jobs_uuid_unique", Unique = true)]
        [Size(255)]
        public string uuid
        {
            get { return fuuid; }
            set { SetPropertyValue<string>(nameof(uuid), ref fuuid, value); }
        }
        string fconnection;
        [Size(SizeAttribute.Unlimited)]
        public string connection
        {
            get { return fconnection; }
            set { SetPropertyValue<string>(nameof(connection), ref fconnection, value); }
        }
        string fqueue;
        [Size(SizeAttribute.Unlimited)]
        public string queue
        {
            get { return fqueue; }
            set { SetPropertyValue<string>(nameof(queue), ref fqueue, value); }
        }
        string fpayload;
        [Size(SizeAttribute.Unlimited)]
        public string payload
        {
            get { return fpayload; }
            set { SetPropertyValue<string>(nameof(payload), ref fpayload, value); }
        }
        string fexception;
        [Size(SizeAttribute.Unlimited)]
        public string exception
        {
            get { return fexception; }
            set { SetPropertyValue<string>(nameof(exception), ref fexception, value); }
        }
    }

}
