//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba1.prueba
{

    [Persistent(@"migrations")]
    public partial class Migrations : XPLiteObject
    {
        uint fid;
        [Key]
        public uint id
        {
            get { return fid; }
            set { SetPropertyValue<uint>(nameof(id), ref fid, value); }
        }
        string fmigration;
        [Size(255)]
        public string migration
        {
            get { return fmigration; }
            set { SetPropertyValue<string>(nameof(migration), ref fmigration, value); }
        }
        int fbatch;
        public int batch
        {
            get { return fbatch; }
            set { SetPropertyValue<int>(nameof(batch), ref fbatch, value); }
        }
    }

}
