//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba1.prueba
{

    [Persistent(@"mora")]
    public partial class Mora : XPLiteObject
    {
        int fidmora;
        [Key(true)]
        public int idmora
        {
            get { return fidmora; }
            set { SetPropertyValue<int>(nameof(idmora), ref fidmora, value); }
        }
        double fmonto;
        public double monto
        {
            get { return fmonto; }
            set { SetPropertyValue<double>(nameof(monto), ref fmonto, value); }
        }
        DateTime ffecha;
        public DateTime fecha
        {
            get { return ffecha; }
            set { SetPropertyValue<DateTime>(nameof(fecha), ref ffecha, value); }
        }
        Prestamo fidprestamo;
        [Association(@"MoraReferencesPrestamo")]
        public Prestamo idprestamo
        {
            get { return fidprestamo; }
            set { SetPropertyValue<Prestamo>(nameof(idprestamo), ref fidprestamo, value); }
        }
        double fsaldo;
        public double saldo
        {
            get { return fsaldo; }
            set { SetPropertyValue<double>(nameof(saldo), ref fsaldo, value); }
        }
    }

}
