//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba1.prueba
{

    [Persistent(@"prestamo")]
    public partial class Prestamo : XPLiteObject
    {
        int fprestamoid;
        [Key(true)]
        public int prestamoid
        {
            get { return fprestamoid; }
            set { SetPropertyValue<int>(nameof(prestamoid), ref fprestamoid, value); }
        }
        float fmonto;
        public float monto
        {
            get { return fmonto; }
            set { SetPropertyValue<float>(nameof(monto), ref fmonto, value); }
        }
        float finteres;
        public float interes
        {
            get { return finteres; }
            set { SetPropertyValue<float>(nameof(interes), ref finteres, value); }
        }
        int fplazo;
        public int plazo
        {
            get { return fplazo; }
            set { SetPropertyValue<int>(nameof(plazo), ref fplazo, value); }
        }
        DateTime ffechainicial;
        public DateTime fechainicial
        {
            get { return ffechainicial; }
            set { SetPropertyValue<DateTime>(nameof(fechainicial), ref ffechainicial, value); }
        }
        float fmonto_a_pagar;
        public float monto_a_pagar
        {
            get { return fmonto_a_pagar; }
            set { SetPropertyValue<float>(nameof(monto_a_pagar), ref fmonto_a_pagar, value); }
        }
        float fmonto_pendiente;
        public float monto_pendiente
        {
            get { return fmonto_pendiente; }
            set { SetPropertyValue<float>(nameof(monto_pendiente), ref fmonto_pendiente, value); }
        }
        bool factivo;
        public bool activo
        {
            get { return factivo; }
            set { SetPropertyValue<bool>(nameof(activo), ref factivo, value); }
        }
        Cliente fcliente_clienteid;
        [Association(@"PrestamoReferencesCliente")]
        public Cliente cliente_clienteid
        {
            get { return fcliente_clienteid; }
            set { SetPropertyValue<Cliente>(nameof(cliente_clienteid), ref fcliente_clienteid, value); }
        }
        Cobrador fcobrador_idCobrador;
        [Association(@"PrestamoReferencesCobrador")]
        public Cobrador cobrador_idCobrador
        {
            get { return fcobrador_idCobrador; }
            set { SetPropertyValue<Cobrador>(nameof(cobrador_idCobrador), ref fcobrador_idCobrador, value); }
        }
        Cuenta fcuenta_idCuenta;
        [Association(@"PrestamoReferencesCuenta")]
        public Cuenta cuenta_idCuenta
        {
            get { return fcuenta_idCuenta; }
            set { SetPropertyValue<Cuenta>(nameof(cuenta_idCuenta), ref fcuenta_idCuenta, value); }
        }
        Prestamo frenovacion;
        [Association(@"PrestamoReferencesPrestamo")]
        public Prestamo renovacion
        {
            get { return frenovacion; }
            set { SetPropertyValue<Prestamo>(nameof(renovacion), ref frenovacion, value); }
        }
        string fmoneda;
        [Size(45)]
        public string moneda
        {
            get { return fmoneda; }
            set { SetPropertyValue<string>(nameof(moneda), ref fmoneda, value); }
        }
        bool fmalo;
        public bool malo
        {
            get { return fmalo; }
            set { SetPropertyValue<bool>(nameof(malo), ref fmalo, value); }
        }
        int ftipopago;
        public int tipopago
        {
            get { return ftipopago; }
            set { SetPropertyValue<int>(nameof(tipopago), ref ftipopago, value); }
        }
        DateTime ffechafin;
        public DateTime fechafin
        {
            get { return ffechafin; }
            set { SetPropertyValue<DateTime>(nameof(fechafin), ref ffechafin, value); }
        }
        int festado;
        public int estado
        {
            get { return festado; }
            set { SetPropertyValue<int>(nameof(estado), ref festado, value); }
        }
        int fdia_pago;
        public int dia_pago
        {
            get { return fdia_pago; }
            set { SetPropertyValue<int>(nameof(dia_pago), ref fdia_pago, value); }
        }
        DateTime ffecha_creacion;
        public DateTime fecha_creacion
        {
            get { return ffecha_creacion; }
            set { SetPropertyValue<DateTime>(nameof(fecha_creacion), ref ffecha_creacion, value); }
        }
        float fmonto_cuota;
        public float monto_cuota
        {
            get { return fmonto_cuota; }
            set { SetPropertyValue<float>(nameof(monto_cuota), ref fmonto_cuota, value); }
        }
        double fpendiente;
        public double pendiente
        {
            get { return fpendiente; }
            set { SetPropertyValue<double>(nameof(pendiente), ref fpendiente, value); }
        }
        int fdia_pago1;
        public int dia_pago1
        {
            get { return fdia_pago1; }
            set { SetPropertyValue<int>(nameof(dia_pago1), ref fdia_pago1, value); }
        }
        int fdia_pago2;
        public int dia_pago2
        {
            get { return fdia_pago2; }
            set { SetPropertyValue<int>(nameof(dia_pago2), ref fdia_pago2, value); }
        }
        int fseguro;
        public int seguro
        {
            get { return fseguro; }
            set { SetPropertyValue<int>(nameof(seguro), ref fseguro, value); }
        }
        [Association(@"CuotasReferencesPrestamo")]
        public XPCollection<Cuotas> CuotasCollection { get { return GetCollection<Cuotas>(nameof(CuotasCollection)); } }
        [Association(@"MoraReferencesPrestamo")]
        public XPCollection<Mora> Moras { get { return GetCollection<Mora>(nameof(Moras)); } }
        [Association(@"PagosReferencesPrestamo")]
        public XPCollection<Pagos> PagosCollection { get { return GetCollection<Pagos>(nameof(PagosCollection)); } }
        [Association(@"PrestamoReferencesPrestamo")]
        public XPCollection<Prestamo> PrestamoCollection { get { return GetCollection<Prestamo>(nameof(PrestamoCollection)); } }
    }

}
