//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba1.prueba
{

    [Persistent(@"proforma")]
    public partial class Proforma : XPLiteObject
    {
        int fidproforma;
        [Key(true)]
        public int idproforma
        {
            get { return fidproforma; }
            set { SetPropertyValue<int>(nameof(idproforma), ref fidproforma, value); }
        }
        string fmonto;
        [Size(45)]
        public string monto
        {
            get { return fmonto; }
            set { SetPropertyValue<string>(nameof(monto), ref fmonto, value); }
        }
        string ffecha;
        [Size(45)]
        public string fecha
        {
            get { return ffecha; }
            set { SetPropertyValue<string>(nameof(fecha), ref ffecha, value); }
        }
        string fnumcuota;
        [Size(45)]
        public string numcuota
        {
            get { return fnumcuota; }
            set { SetPropertyValue<string>(nameof(numcuota), ref fnumcuota, value); }
        }
        string fsaldo;
        [Size(45)]
        public string saldo
        {
            get { return fsaldo; }
            set { SetPropertyValue<string>(nameof(saldo), ref fsaldo, value); }
        }
    }

}
