//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba1.prueba
{

    [Persistent(@"referencias")]
    public partial class Referencias : XPLiteObject
    {
        int fidreferencias;
        [Key(true)]
        public int idreferencias
        {
            get { return fidreferencias; }
            set { SetPropertyValue<int>(nameof(idreferencias), ref fidreferencias, value); }
        }
        string fnombre_referencia;
        [Size(200)]
        public string nombre_referencia
        {
            get { return fnombre_referencia; }
            set { SetPropertyValue<string>(nameof(nombre_referencia), ref fnombre_referencia, value); }
        }
        string ftelefono_referencia;
        [Size(45)]
        public string telefono_referencia
        {
            get { return ftelefono_referencia; }
            set { SetPropertyValue<string>(nameof(telefono_referencia), ref ftelefono_referencia, value); }
        }
        string fparentesco_referencia;
        [Size(45)]
        public string parentesco_referencia
        {
            get { return fparentesco_referencia; }
            set { SetPropertyValue<string>(nameof(parentesco_referencia), ref fparentesco_referencia, value); }
        }
        string fdireccion_referencia;
        [Size(200)]
        public string direccion_referencia
        {
            get { return fdireccion_referencia; }
            set { SetPropertyValue<string>(nameof(direccion_referencia), ref fdireccion_referencia, value); }
        }
        Cliente fclienteid;
        [Association(@"ReferenciasReferencesCliente")]
        public Cliente clienteid
        {
            get { return fclienteid; }
            set { SetPropertyValue<Cliente>(nameof(clienteid), ref fclienteid, value); }
        }
        string fnombre_completo;
        [Size(200)]
        public string nombre_completo
        {
            get { return fnombre_completo; }
            set { SetPropertyValue<string>(nameof(nombre_completo), ref fnombre_completo, value); }
        }
        string ftelefono;
        [Size(45)]
        public string telefono
        {
            get { return ftelefono; }
            set { SetPropertyValue<string>(nameof(telefono), ref ftelefono, value); }
        }
        string fparentesco;
        [Size(45)]
        public string parentesco
        {
            get { return fparentesco; }
            set { SetPropertyValue<string>(nameof(parentesco), ref fparentesco, value); }
        }
        string fdireccion;
        [Size(20)]
        public string direccion
        {
            get { return fdireccion; }
            set { SetPropertyValue<string>(nameof(direccion), ref fdireccion, value); }
        }
    }

}
