//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba1.prueba
{

    [Persistent(@"telefono")]
    public partial class Telefono : XPLiteObject
    {
        int fidtelefono;
        [Key(true)]
        public int idtelefono
        {
            get { return fidtelefono; }
            set { SetPropertyValue<int>(nameof(idtelefono), ref fidtelefono, value); }
        }
        string fnumero;
        [Size(20)]
        public string numero
        {
            get { return fnumero; }
            set { SetPropertyValue<string>(nameof(numero), ref fnumero, value); }
        }
        string fdescripcion;
        [Size(45)]
        public string descripcion
        {
            get { return fdescripcion; }
            set { SetPropertyValue<string>(nameof(descripcion), ref fdescripcion, value); }
        }
        Cliente fclienteid;
        [Association(@"TelefonoReferencesCliente")]
        public Cliente clienteid
        {
            get { return fclienteid; }
            set { SetPropertyValue<Cliente>(nameof(clienteid), ref fclienteid, value); }
        }
    }

}
