//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Prueba1.prueba
{

    [Persistent(@"usuario")]
    public partial class Usuario : XPLiteObject
    {
        int fusuarioid;
        [Key(true)]
        public int usuarioid
        {
            get { return fusuarioid; }
            set { SetPropertyValue<int>(nameof(usuarioid), ref fusuarioid, value); }
        }
        string fNombre;
        [Size(45)]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fpassword;
        [Size(45)]
        public string password
        {
            get { return fpassword; }
            set { SetPropertyValue<string>(nameof(password), ref fpassword, value); }
        }
        string ftipo;
        [Size(45)]
        public string tipo
        {
            get { return ftipo; }
            set { SetPropertyValue<string>(nameof(tipo), ref ftipo, value); }
        }
    }

}
