//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PRUEBA.mydb
{

    [Persistent(@"cedula")]
    public partial class Cedula : XPLiteObject
    {
        int fidCedula;
        [Key]
        public int idCedula
        {
            get { return fidCedula; }
            set { SetPropertyValue<int>(nameof(idCedula), ref fidCedula, value); }
        }
        string fCedulacol;
        [Size(45)]
        public string Cedulacol
        {
            get { return fCedulacol; }
            set { SetPropertyValue<string>(nameof(Cedulacol), ref fCedulacol, value); }
        }
        string fNomnbre;
        [Size(45)]
        public string Nomnbre
        {
            get { return fNomnbre; }
            set { SetPropertyValue<string>(nameof(Nomnbre), ref fNomnbre, value); }
        }
        Nacionalidad fNACIONALIDAD_idtable1;
        [Association(@"CedulaReferencesNacionalidad")]
        public Nacionalidad NACIONALIDAD_idtable1
        {
            get { return fNACIONALIDAD_idtable1; }
            set { SetPropertyValue<Nacionalidad>(nameof(NACIONALIDAD_idtable1), ref fNACIONALIDAD_idtable1, value); }
        }
    }

}
