//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PRUEBA.mydb
{

    [Persistent(@"nacionalidad")]
    public partial class Nacionalidad : XPLiteObject
    {
        int fidtable1;
        [Key]
        public int idtable1
        {
            get { return fidtable1; }
            set { SetPropertyValue<int>(nameof(idtable1), ref fidtable1, value); }
        }
        string fPais;
        [Size(45)]
        public string Pais
        {
            get { return fPais; }
            set { SetPropertyValue<string>(nameof(Pais), ref fPais, value); }
        }
        string fciudad;
        [Size(45)]
        public string ciudad
        {
            get { return fciudad; }
            set { SetPropertyValue<string>(nameof(ciudad), ref fciudad, value); }
        }
        [Association(@"CedulaReferencesNacionalidad")]
        public XPCollection<Cedula> Cedulas { get { return GetCollection<Cedula>(nameof(Cedulas)); } }
    }

}
